name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 安装依赖
      run: |
        npm install
        npx hexo g
    - name: 提交
      run: |
        cd ./public
        git init
        git config user.name "ZQ-jhon"
        git config user.email "350037310@qq.com"
        git add .
        git commit -m "Update with github action"
    - name: 推送
      run: git push --force --quiet "https://${{secret.stroke}}@${{secret.thisRepo}}" master:master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
