name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 安装依赖
      run: |
        npm install
        npx hexo g
    - name: 提交
      run: |
        cd ./public
        git init
        git config user.name "ZQ-jhon"
        git config user.email "350037310@qq.com"
        git add .
        git commit -m "Update Readme docs to static html with TRAVIS-CI."
    - name: 推送
      run: |
        git remote add origin ${{secrets.thisRepo}}
        git push --set-upstream origin master
        git push
        
