name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 安装依赖
      run: |
        npm install
        npx hexo g
    - name: 提交
      run: |
        cd ./public
        git init
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        - cd ./public
    - name: 推送
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
