name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean install dependencies and build
        run: |
          sudo npm install -g hexo-cli
          sudo npm install
          sudo hexo g
          sudo cd ./public
          sudo git init
          sudo git config user.name "ZQ-jhon"
          sudo git config user.email "350037310@qq.com"
          sudo git add .
          sudo git commit -m "Update with Github Action."
          sudo git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    env: 
      githubAction: ${{ secrets.githubAction }}
    
