name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean install dependencies and build
        run: |
          npm install -g hexo-cli
          npm install
          hexo g
          cd ./public
          git init
          git config user.name "ZQ-jhon"
          git config user.email "350037310@qq.com"
          git add .
          git commit -m "Update with Github Action."
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    env: 
      githubAction: ${{ secrets.githubAction }}
    
