name: Node CI

on: 
  push:
    branches: 'hexo'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for hexo
      uses: heowc/action-hexo@1.0.2
      env:
        name: 'ZQ-jhon'
        email: '350037310@qq.com'
